### ISSUE TITLE
Make lobby customisable

### ISSUE THREAD

**Issue by icidasset** [fission-suite/auth-lobby#45]
Initial idea, let people pass a `theme` param to the auth lobby so people can customise it. That param should point to a JSON config file (via url or cid).

```json
{
  "logo": "URL_TO_IMAGE_OR_CID",
  "introduction": "markdown",
  "colors": {
    "accent": "#ff0"
  },
  "text": {
    "authorisation": {
      "resources": "Allow {{APP_NAME_OR_ORIGIN}} access to the following for about {{DURATION}}?",
      "no_resources": "Allow {{ORIGIN}} to authenticate with this account?"
    }
  }
}
```

Not sure about `colors`, I think I'll start with being able to replace the purple and keep the neutral colors. It's either everything or just one color. If we start allowing customisation of the background and text colors, you'd need to think of every variant (such as the subtle foot note color) or some text won't readable anymore. Might do later, we'll see.

Implement this in chunks, start with the simple stuff.

**Comment by therealjeffg** [comment]
> Not sure about colors, I think I'll start with being able to replace the purple and keep the neutral colors.

If we look at simple theming systems for other apps, the one that immediately pops to mind is slack themes which is literally just a set of CSS colours provided by the user. Working up from your example of a single highlight colour, maybe there's a subset of a few colours the developer can provide to give them *enough* flexibility. A more complex example is [Firefox Color](https://color.firefox.com/) but it's still just a set of colors and potentially an image. I agree that bad things can happen if a developer provides eg all black to produce an unreadable UI, but we have to assume that most developers won't do something that impairs functionality, and otherwise get out of their way.

**Comment by icidasset** [comment]
Very basic theming is implemented https://github.com/fission-suite/auth-lobby#theming, could be extended later with colors and more text replacements.
